---
apiVersion: v1
kind: Service

metadata:
  name: web
  labels:
    app: web

spec:
#  type: LoadBalancer
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80 # send to envoy proxy; change to 8080 to send to web directly
