#!/usr/bin/env python3
import requests
import json
import yaml
import sys

with open("config.yaml", "r") as ymlfile:
    config = yaml.load(ymlfile,Loader=yaml.FullLoader)

harness = {
    "infraDef": "cluster01",  # workflow.variables.InfraDefinition_KUBERNETES
    "cpu": sys.argv[1],  # ${workflow.variables.cpu}
    "mem": sys.argv[2],  # ${workflow.variables.mem}
    "adjust": "True",  # ${workflow.variables.adjust}
    "name": "canary",  # ${workflow.variables.name}
    "buildNo": "200",  # ${artifact.buildNo}
    "service": "web-canary-deployment",  # ${service.name}
    "token": config['adjust']['token'],
    "accountId": config['harness']['accountId'],
    "application": config['harness']['application'],
    "apiKey": config['harness']['apiKey'],
}

url = f"https://app.harness.io/gateway/api/webhooks/{harness['token']}?accountId={harness['accountId']}"
headers = {"content-type": "application/json"}
data = {
    "application": harness["application"],
    "parameters": {
        "Service": harness["service"],
        "InfraDefinition_KUBERNETES": harness["infraDef"],
        "cpu": harness["cpu"],
        "mem": harness["mem"],
        "adjust": harness["adjust"],
        "name": harness["name"],
    },
    "artifacts": [
        {
            "service": harness["service"],
            "buildNumber": f"web-canary-deployment_{harness['buildNo']}",
        }
    ],
}

trigger_result = requests.post(url, json=data, headers=headers).json()

requestId = trigger_result["requestId"]
apiUrl = trigger_result["apiUrl"]

headers = {
    "X-API-KEY": harness["apiKey"],
    "content-type": "application/json",
}
 
harness_api_url = apiUrl.replace("https://app.harness.io/api/","https://app.harness.io/gateway/api/")

state = requests.get(url=harness_api_url, headers=headers).json()
print(state)
